[package]
name = "gcal_notifs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
daemonize = "0.5.0"
notify-rust = "4.9.0"
rodio = "0.17.1"
