[package]
name = "gcal_notifs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
daemonize = "0.5.0"
notify-rust = "4.9.0"
